Goal 1 - Error 4: Users Model - NameError: uninitialized constant UsersController::User     app/controllers/users_controller.rb:4:in 'new'   1) This error is happening because in line 4 of the Users Controller, in the new action, User is not defined. - To fix this error:   1) Generate a User Model
- The next error: ActionView::Template::Error: undefined method 'users_path' for #<#<Class:0x007fdb37a29cb0>:0x007fdb37a33cb0>
  1) This error is happening because no path has been defined for new users that are created
- To fix this error:
  1) Create a new route for the Create action